// 2: add here

export enum Icons {
  grid7 = 'grid7',
  grid8 = 'grid8',
  health = 'health',
  calendar = 'calendar',
  book = 'book',
  setting2 = 'setting2',
  messageQuestion = 'messageQuestion',
  search = 'search',
  profile2User = 'profile2User',
  teacher = 'teacher',
  arrowOutward = 'arrowOutward',
  location = 'location',
  eclise = 'eclise',
  arrowDown = 'arrowDown',
  notificationBell = 'notificationBell',
  add = 'add',
  arrowLeft = 'arrowLeft',
  arrowRight = 'arrowRight',
  calendar2 = 'calendar2',
  export = 'export',
  gridEraser = 'gridEraser',
  more = 'more',
  saveAdd = 'saveAdd',
  smallCheck = 'smallCheck',
  mail = 'mail',
  alertCircle = 'alertCircle',
  check = 'check',
  warning2 = 'warning2',
  information = 'information',
  danger = 'danger',
  loader2 = 'loader2',
  hamburger = 'hamburger',
  documentText = 'documentText',
  trash = 'trash',
  security = 'security',
  userEdit = 'userEdit',
  ageIcon = 'ageIcon',
  blood = 'blood',
  gender = 'gender',
  habit = 'habit',
  healthIcon2 = 'healthIcon2',
  measurement = 'measurement',
  primary = 'primary',
  waist = 'waist',
  weight = 'weight',
  clock = 'clock',
  calendarEdit = 'calendarEdit',
  calendarTick = 'calendarTick',
  closeSquare = 'closeSquare',
  timer = 'timer',
  document = 'document',
  helpCircle = 'helpCircle',
  bookmark = 'bookmark',
  play = 'play',
  password = 'password',
}

export { Icons as IconNames }
