import { IconNames as Icons } from './icon-names'

// 3: finally, add here
export const IconMap: Map<string, string> = new Map([
  [Icons.grid7, 'Grid7Icon'],
  [Icons.grid8, 'Grid8Icon'],
  [Icons.health, 'HealthIcon'],
  [Icons.arrowOutward, 'ArrowOutwardIcon'],
  [Icons.book, 'BookIcon'],
  [Icons.calendar, 'CalendarIcon'],
  [Icons.messageQuestion, 'MessageQuestionIcon'],
  [Icons.profile2User, 'Profile2UserIcon'],
  [Icons.search, 'SearchIcon'],
  [Icons.setting2, 'Setting2Icon'],
  [Icons.teacher, 'TeacherIcon'],
  [Icons.location, 'LocationIcon'],
  [Icons.eclise, 'EclipseIcon'],
  [Icons.arrowDown, 'ArrowDownIcon'],
  [Icons.notificationBell, 'NotificationBellIcon'],
  [Icons.add, 'AddIcon'],
  [Icons.arrowLeft, 'ArrowLeftIcon'],
  [Icons.arrowRight, 'ArrowRightIcon'],
  [Icons.calendar2, 'Calendar2Icon'],
  [Icons.export, 'ExportIcon'],
  [Icons.gridEraser, 'GridEraserIcon'],
  [Icons.more, 'MoreIcon'],
  [Icons.saveAdd, 'SaveAddIcon'],
  [Icons.smallCheck, 'SmallCheckIcon'],
  [Icons.mail, 'MailIcon'],
  [Icons.alertCircle, 'AlertCircleIcon'],
  [Icons.check, 'CheckIcon'],
  [Icons.warning2, 'Warning2Icon'],
  [Icons.danger, 'DangerIcon'],
  [Icons.information, 'InformationIcon'],
  [Icons.loader2, 'Loader2Icon'],
])
