interface SelectOption {
  label: string
  value: string
}

export interface IStudentsSurveyData {
  gender: SelectOption
  age: number
  birthday: string
  ethnicity: SelectOption
  ethnicityOther?: string
  religion: SelectOption
  religionOther?: string
  classLevel: SelectOption
  distanceToSchool: SelectOption
  yearsAtSchool: SelectOption
  communityName: string
  numberOfChildren: number
  siblingPosition: SelectOption
  fatherOccupation: string
  motherOccupation: string
  livingSituation: SelectOption
  healthProblems: SelectOption
  healthProblemsOther?: string
  healthStatus: SelectOption
  hpvVaccine: SelectOption
  //Effects of smoking and drinking alcohol
  smokingDrinkingEffects: SelectOption
  healthCheckupsImportance: SelectOption
  feelingsOfstress: SelectOption
  stressSigns: SelectOption
  stressEffects: string
  stressCauses: string[]
  snackPreference: SelectOption
  bodySizeBoys: string
  bodySizeGirls: string
  physicalActivityFrequency: string
  doctorVisits: string
  balancedDiet: string
  dietConsequence: string
  carbExamples: string
  proteinExamples: string
  fatExamples: string
  vitaminExamples: string
  sweetsEffect: string
  saltyFoodEffect: string
  physicalActivity: string
  activityBenefits: string
  dietConsequenceSpecify: string
  exerciseActivities: string[]
  sweetsEffectSpecify: string
  saltyFoodEffectSpecify: string
  activityBenefitsSpecify: string
  smokingDrinkingEffectsSpecify: string
  healthCheckupsImportanceSpecify: string
  feelingsOfstressSpecify: string
  stressSignsSpecify: string
  balancedDietImportance: SelectOption
  eatingHealthyFoods: SelectOption
  idealBodySizeBoys: SelectOption
  idealBodySizeBoysSpecify: string
  idealBodySizeGirls: SelectOption
  idealBodySizeGirlsSpecify: string
  regularPhysicalActivity: SelectOption
  barriersToPhysicalActivity: string
  importanceOfPhysicalActivity: SelectOption
  suitableActivitiesBoys: string
  suitableActivitiesGirls: string
  fruitsVegetables: SelectOption
  snacksConsumption: SelectOption
  sugaryBeverages: SelectOption
  physicalActivityDuration: SelectOption
  physicalActivityTypes: string[]
  houseChoresFrequency: SelectOption
  houseChoresTypes: string[]
  outsidePhysicalActivitiesFrequency: SelectOption
  mobileGamesHours: string
  tvGamesHours: string
  bedtime: string
  wakeupTime: string
  doctorVisitsFrequency: SelectOption
  copingMechanisms: string[]
  stressFactors: string[]
  smokingHistory: SelectOption
  currentSmoking: SelectOption
  alcoholHistory: SelectOption
  currentAlcohol: SelectOption
}
