export const csvHeaders = [
  { label: 'User Id', key: 'userId' },
  { label: 'ID', key: 'id' },
  { label: 'Full Name', key: 'fullName' },
  { label: 'Age', key: 'age' },
  { label: 'Gender', key: 'gender' },
  { label: 'Parent Mobile', key: 'parentMobile' },
  { label: 'Class', key: 'level' },
  { label: 'Height', key: 'latestHealthData.height' },
  { label: 'Weight', key: 'latestHealthData.weight' },
  { label: 'Waist', key: 'latestHealthData.waist' },
  { label: 'BMI', key: 'latestHealthData.bmi' },
  { label: 'Blood Pressure', key: 'latestHealthData.bloodPressure' },
  { label: 'Cholesterol', key: 'latestHealthData.cholesterol' },
  { label: 'Glucose Level', key: 'latestHealthData.glucoseLevel' },
  { label: 'State', key: 'state' },
  { label: 'LGA', key: 'lga' },
  { label: 'School', key: 'school' },
]

export const excelHeaders = [
  { header: 'User Id', key: 'userId', width: 20 },
  { header: 'ID', key: 'id', width: 20 },
  { header: 'Full Name', key: 'fullName', width: 40 },
  { header: 'Age', key: 'age', width: 10 },
  { header: 'Gender', key: 'gender', width: 15 },
  { header: 'Parent Mobile', key: 'parentMobile', width: 20 },
  { header: 'Class', key: 'level', width: 15 },
  { header: 'Height', key: 'latestHealthData.height', width: 10 },
  { header: 'Weight', key: 'latestHealthData.weight', width: 10 },
  { header: 'Waist', key: 'latestHealthData.waist', width: 10 },
  { header: 'BMI', key: 'latestHealthData.bmi', width: 10 },
  {
    header: 'Blood Pressure',
    key: 'latestHealthData.bloodPressure',
    width: 10,
  },
  { header: 'Cholesterol', key: 'latestHealthData.cholesterol', width: 10 },
  { header: 'Glucose Level', key: 'latestHealthData.glucoseLevel', width: 10 },
  { header: 'State', key: 'state', width: 15 },
  { header: 'LGA', key: 'lga', width: 15 },
  { header: 'School', key: 'school', width: 10 },
]
