import Providers from '@/context'
import './globals.css'
import type { Metadata } from 'next'
import CustomToaster from '@/components/custom-toaster'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <CustomToaster />
        </Providers>
      </body>
    </html>
  )
}
